### ISSUE TITLE
请问注解生成的接口如何打包进去

### ISSUE THREAD

**Issue by Aucean** [EastWoodYang/Mis#11]
我现在有个需求是实现个注解处理器，通过注解自动生成要暴露的接口。现在的问题是你打这api包是在编译之前，也就是注解处理器处理之前就打好包了，那么我注解处理器生成的接口如何打到api包？

**Comment by EastWoodYang** [comment]
对的，有点不解的是接口为什么要通过注解生成？另外，注解处理器好像也不能将接口生成在mis目录下吧？

**Comment by EastWoodYang** [comment]
方便的话，可以加下我的微信: Lord-with-us

**Comment by Simon1121** [comment]
这个和我提的：在kotlin中使用@Parcelize注解可序列化类的问题类似？
