### ISSUE TITLE
mis time out

### ISSUE THREAD

**Issue by wang-neng** [EastWoodYang/Mis#12]
Caused by: org.gradle.api.GradleException: Timed out when compile mis java source to bytecode with command.

**Comment by wang-neng** [comment]
at com.eastwood.tools.plugins.mis.core.JarUtil.generateJavaSourceJar(JarUtil.groovy:162)
	at com.eastwood.tools.plugins.mis.core.JarUtil.packJavaSourceJar(JarUtil.groovy:62)
	at com.eastwood.tools.plugins.mis.core.JarUtil$packJavaSourceJar.call(Unknown Source)
	at com.eastwood.tools.plugins.mis.MisPlugin.handleLocalJar(MisPlugin.groovy:229)
	at com.eastwood.tools.plugins.mis.MisPlugin$_apply_closure4$_closure21.doCall(MisPlugin.groovy:110)

**Comment by EastWoodYang** [comment]
抱歉，已经 定位到问题，我这边设置了编译超时时间，时间有点短，我增加一下。

**Comment by wang-neng** [comment]
1、超时时间是一个问题
2、假如项目中需要编译的java文件中绝对路径目录(文件夹命中中存在空格符号)，使用javac -d 路径\xxx.java  ,
编译失败

 if (!javaFiles.isEmpty()) {
            def command = "javac " + (keepParameters ? "-parameters" : "") + " -d . -encoding UTF-8 -target " + compileOptions.targetCompatibility.toString() + " -source " + compileOptions.sourceCompatibility.toString() + (classPath.size() > 0 ? (" -classpath " + classPath.join(classpathSeparator) + " ") : "") + javaFiles.join(' ')
            def p = (command).execute(null, classesDir)

            def result = p.waitFor(30, TimeUnit.SECONDS)
            if (!result) {
                throw new GradleException("Timed out when compile mis java source to bytecode with command.\nExecute command:\n" + command)
            }

            if (p.exitValue() != 0) {
                throw new GradleException("Failure to compile mis java source to bytecode: \n" + p.err.text + "\nExecute command:\n" + command)
            }
        }

编译信息：
/------------------------------------------------------------------/
javac -parameters -d . -encoding UTF-8 -target 1.8 -source 1.8 -classpath D:\Program Files\Android\sdk\platforms\android-28\android.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\androidx.appcompat\appcompat\1.0.0\155b5a7193b5b87c3ece2ec444c85cd8de2347d
/--------------------------------------------------------------------/
Program Files文件夹名称中存在空格，会导致javac -d 目录/.../XXX.java   编译成class文件失败

**Comment by EastWoodYang** [comment]
好的，收到
