### ISSUE TITLE
mis目录下某些kotlin语法不支持

### ISSUE THREAD

**Issue by xiaofan-wxf** [EastWoodYang/Mis#13]
使用过程中想尝试下暴露我的一些实现类。类似以下这种语法放在mis目录下暴露出去时，都会报错。作者可以试下，看上去是KotlinToJVMBytecodeCompiler 对这种语法还不支持？
```
class Test {
     val flag = false
    fun aaa(aaa: String) {
        when(aaa){ // 此处报错
            "1" -> println("---------1")
            "2" -> println("---------1")
            "3" -> println("---------1")
        }
    }

   fun bbb(){
         return if (flag) { //此处报错
              null
          } else {

         }
  }
}
```

异常：org.jetbrains.kotlin.utils.KotlinExceptionWithAttachments: Exception while analyzing expression at xxxxx

**Comment by EastWoodYang** [comment]
收到！

**Comment by EastWoodYang** [comment]
我这边 好像OK，你那边com.android.tools.build:gradle版本多少

**Comment by xiaofan-wxf** [comment]
> 我这边 好像OK，你那边com.android.tools.build:gradle版本多少

试了下，的确是跟版本有关系 我这里升级到最新版本了 com.android.tools.build:gradle:4.0.2

**Comment by EastWoodYang** [comment]
好的，我这边发布了新版本v2.1.0，你那边可以更新下
