### ISSUE TITLE
请问,如果不使用autoInject 如何注册服务

### ISSUE THREAD

**Issue by hf529270451** [EastWoodYang/Mis#6]

**Comment by hf529270451** [comment]
项目中有AutoRegist 插件，但是autoRegist插件不起作用 无法扫描到service里面的类

**Comment by EastWoodYang** [comment]
可以考虑下AutoInject嘛（哈哈哈哈哈），AutoRegist我没具体使用过，不很清楚。

**Comment by hf529270451** [comment]
请问可以在主模块使用 MisService.register(ILibraryService.class, Class.forName("com.xxx.ILibraryServiceImpl")); 注册吗  为啥提示我classNotFoundException

**Comment by hf529270451** [comment]
运行demo报错 mainActivity空指针
 library中的MisAutoArrowBow 没有运行 导致mainActivity中的libraryModel空指针 ，请问是我的步骤有问题吗？请帮忙看看，多谢

第一步：
我在library中的配置

    mis {
     publications {
        main {
            groupId 'com.eastwood.demo'
            artifactId 'library-sdk'
            version '1.0.0' // 初次配置时不设置，发布至maven时设置

            dependencies {
                 implementation 'com.google.code.gson:gson:2.8.1'
            }
        }
     }

     repositories {
        maven {
            mavenLocal()
        }
     }
    }

然后点击了publishMis...toLocal

第二步：
app中这样引用的：

    implementation misPublication('com.eastwood.demo:library-sdk:1.0.0')

然后运行 就空指针了

**Comment by EastWoodYang** [comment]
你加我下 qq 1056453754

**Comment by EastWoodYang** [comment]
我试用了下AutoRegister，好像不支持多个入参，所以mis无法使用AutoRegister来完成注册。

------------------------------

你检查下 主工程build.gradle 是否 添加了 

apply plugin: 'auto-inject'
autoInject {
    showLog = true //开启日志 编译时检查下日志输出
    ignorePackages = ['android', 'com/google']
}

另外 mavenLocal()不是添加在 mis{ }中的，而应该是

 allprojects {
    repositories {
        jcenter()
        google()
        mavenLocal()
    }
}

**Comment by hf529270451** [comment]
您好，我加了您的QQ 您看您方便解答一下吗。  我把mavenLocal去了 还是会报错。。。

并且在project 的build.gradle中添加了


     allprojects {
      repositories {
          jcenter()
          google()
          mavenLocal()
      }
     }

**Comment by EastWoodYang** [comment]
没收到好友请求
