### ISSUE TITLE
配置maven发布属性时报错

### ISSUE THREAD

**Issue by Simon1121** [EastWoodYang/Mis#7]
org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':app:previewRuntimeClasspath'

module 的build.gradle 配置了一个buildType 为preview，有关？改怎么解决

**Comment by EastWoodYang** [comment]
你试一下为所有Module都配上buildType 为preview

**Comment by EastWoodYang** [comment]
已在v1.5.0中修复
